var TRANSLATE = {
    "en": {
        "messages": {
            "fullname": "- required field<br>- field must contain only letters",
            "firstname": "- required field<br>- name length 2-26 characters<br>- field must contain only letters",
            "lastname": "- required field<br>- name length 2-26 characters<br>- field must contain only letters",
            "email": "- field must contain a valid email address",
            "phone": "- number entered incorrectly",
            "conditions": "Please confirm your agreement with conditions",
            "success": "Everything was successful, we congratulate you!",
            "error": "Unfortunately, the sending was not successful",
            "limit": "Unfortunately, sending limit has expired",
            "code": "You entered an incorrect code",
            "required": "Required field",
            0: "We congratulate you with successful registration. Your assigned manager will contact you.",
            1: "We congratulate you with successful registration. Your assigned manager will contact you. You will be redirected to your personal account in a few seconds.",
            2: "Your email address was previously used for registration in our system. Please try a different email.",
            3: "We congratulate you with successful registration. Your assigned manager will contact you.",
            4: "Unfortunately, there was an error during registration. Please try again later.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "We congratulate you with successful registration. Our system is busy at the moment. Your assigned manager will contact you.",
            7: "Unfortunately, your registration data cannot be accepted by our system. Please try filling out the form with different data."
        },
        "preferredCountryList": ["gb", "ie", "fr", "be", "nl"],
        "country": "gb"
    },
    "ru": {
        "messages": {
            "fullname": "- поле обязательно для заполнения<br>- поле должно содержать только буквы",
            "firstname": "- поле обязательно для заполнения<br>- длина имени 2-26 символов<br>- поле должно содержать только буквы",
            "lastname": "- поле обязательно для заполнения<br>- длина имени 2-26 символов<br>- поле должно содержать только буквы",
            "email": "- поле должно содержать правильный email-адрес",
            "phone": "- поле должно содержать корректный номер телефона",
            "conditions": "Пожалуйста, подтвердите ваше согласие с условиями",
            "success": "Ваша регистрация прошла успешно, поздравляем Вас! Ожидайте звонка в ближайшее время.",
            "error": "К сожалению, регистрация не прошла успешно",
            "limit": "К сожалению, лимит на отправку формы исчерпан",
            "code": "поле должно содержать правильный код",
            "required": "поле обязательно для заполнения",
            0: "Поздравляем с успешной регистрацией. Ваш личный консультант свяжется с Вами в ближайшее время.",
            1: "Поздравляем с успешной регистрацией. Ваш личный консультант свяжется с Вами в ближайшее время. Через несколько секунд Вы будете перенаправлены в личный кабинет.",
            2: "Ваш адрес электронной почты уже зарегистрирован в системе. Пожалуйста, попробуйте другой адрес.",
            3: "Поздравляем с успешной регистрацией. Ваш личный консультант свяжется с Вами в ближайшее время.",
            4: "К сожалению, при регистрации произошла ошибка. Пожалуйста, попробуйте позже.",
            5: "К сожалению, в данный момент нет подходящих для Вас брокеров.",
            6: "Поздравляем с успешной регистрацией. К сожалению, система в данный момент недоступна. Ваш личный консультант свяжется с Вами в ближайшее время.",
            7: "К сожалению, введенные Вами данные не могут быть приняты системой. Попробуйте другие регистрационные данные."
        },
        "preferredCountryList": ["kz", "ua", "by", "ge"],
        "country": "ru"
    },
    "ar": {
        "messages": {
            "fullname": "- الحقل المطلوب <br> - يجب أن يحتوي الحقل على أحرف فقط",
            "firstname": " الحقل المطلوب ـ <br> طول الاسم 2-26 حرفًا <br> يجب أن يحتوي الحقل على أحرف فقط",
			"lastname": " الحقل مطلوب ـ <br> طول الاسم ـ <br> طول الاسم 2-26 حرفًا <br> يجب أن يحتوي الحقل على أحرف فقط",
			"email": "- ـ يجب أن يحتوي الحقل على عنوان بريد إلكتروني صالح",
			"phone": "- ـ تم إدخال الرقم بشكل غير صحيح",
			"conditions": "الرجاء تأكيد موافقتك على الشروط",
			"success": "كل شيء جيّد، نحن نهنئك!",
			"error": "لسوء الحظ، لم يكن الإرسال ناجحًا",
			"limit": "لسوء الحظ، انتهت صلاحية الإرسال",
			"code": "لقد أدخلت رمزًا غير صحيح",
            "required": "يتطلب حقلا",
            0: "نهنئك بالتسجيل الناجح. سيتصل بك مستشارنا قريبًا",
			1: "نهنئك بالتسجيل الناجح. سيتصل بك مستشارنا قريبًا. ستتم إعادة توجيهك إلى حسابك الشخصي خلال بضع ثوانٍ",
			2: "سبق استخدام عنوان بريدك الإلكتروني للتسجيل في نظامنا. يرجى إدخال عنوان بريد إلكتروني مختلف.",
			3: "نهنئك بالتسجيل الناجح. سيتصل بك مستشارنا قريبًا",
			4: "للأسف، حدث خطأٌ ما أثناء التسجيل. يرجى المحاولة مرة أخرى في وقت لاحق.",
			5: "للأسف ، لا يوجد وسطاء مناسبون لك.",
			6: "نهنئك بالتسجيل الناجح. نظامنا مشغول في الوقت الحالي. سيتواصل مستشارنا بك قريبًا.",
			7: "لسوء الحظ، لا يمكن لنظامنا قبول بيانات التسجيل الخاصة بك. يرجى محاولة ملء نموذج ببيانات مختلف."
        },
        "preferredCountryList": ["ae", "sa", "qa", "kw", "bh", "om"],
        "country": "ae"
    },
    "de": {
        "messages": {
            "fullname": "- Pflichtfeld <br> - Das Feld darf nur Buchstaben enthalten",
            "firstname": "- Pflichtfeld <br> - Namenslänge 2-26 Zeichen <br> - Das Feld darf nur Buchstaben enthalten",
            "lastname": "- Pflichtfeld <br> - Namenslänge 2-26 Zeichen <br> - Das Feld darf nur Buchstaben enthalten",
            "email": "- Das Feld muss eine gültige E-Mail-Adresse enthalten",
            "phone": "- Nummer falsch eingegeben",
            "conditions": "Bitte bestätigen Sie Ihre Zustimmung zu den Bedingungen",
            "success": "Alles war erfolgreich, wir gratulieren Ihnen!",
            "error": "Leider war das Senden nicht erfolgreich",
            "limit": "Leider ist das Sendelimit abgelaufen",
            "code": "Du hast einen falschen Code eingegeben",
            "required": "Pflichtfeld",
            0: "Wir gratulieren Ihnen zur erfolgreichen Registrierung. Unser Berater wird sich in Kürze mit Ihnen in Verbindung setzen.",
            1: "Wir gratulieren Ihnen zur erfolgreichen Registrierung. Unser Berater wird sich in Kürze mit Ihnen in Verbindung setzen. Sie werden in wenigen Sekunden auf Ihr persönliches Konto weitergeleitet.",
            2: "Ihre E-Mail-Adresse wurde zuvor für die Registrierung in Ihrem System verwendet. Bitte versuchen Sie eine andere E-Mail.",
            3: "Wir gratulieren Ihnen zur erfolgreichen Registrierung. Unser Berater wird sich in Kürze mit Ihnen in Verbindung setzen.",
            4: "Leider ist bei der Registrierung ein Fehler aufgetreten. Bitte versuche es später erneut.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Wir gratulieren Ihnen zur erfolgreichen Registrierung. Unser System ist im Moment beschäftigt. Unser Berater wird sich in Kürze mit Ihnen in Verbindung setzen.",
            7: "Leider können Ihre Registrierungsdaten von unserem System nicht akzeptiert werden. Bitte versuchen Sie das Formular mit anderen Daten auszufüllen."
        },
        "preferredCountryList": ["at", "be", "fr", "lu", "it"],
        "country": "de"
    },
    "dk": {
        "messages": {
            "fullname": "- påkrævet felt <br> - felt må kun indeholde bogstaver",
            "firstname": "- påkrævet felt <br> - navnelængde 2-26 tegn <br> - felt må kun indeholde bogstaver",
            "lastname": "- påkrævet felt <br> - navnelængde 2-26 tegn <br> - felt må kun indeholde bogstaver",
            "email": "- feltet skal indeholde en gyldig email adresse",
            "phone": "- nummer indtastet forkert",
            "conditions": "Bekræft venligst din aftale med vilkårene",
            "success": "Alt var vellykket, vi lykønsker dig!",
            "error": "Desværre var afsendelsen ikke succesfuld",
            "limit": "Desværre er afsendelsesgrænsen udløbet",
            "code": "Du indtastede en forkert kode",
            "required": "påkrævet område",
            0: "Vi lykønsker dig med en vellykket registrering. Vores konsulent kontakter dig snarest.",
            1: "Vi lykønsker dig med en vellykket registrering. Vores konsulent kontakter dig snarest. Du bliver omdirigeret til din personlige konto om få sekunder.",
            2: "Your email address was previously used for registration in our system. Please try a different email.",
            3: "Vi lykønsker dig med en vellykket registrering. Vores konsulent kontakter dig snarest.",
            4: "Der var desværre en fejl under registreringen. Prøv igen senere.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Vi lykønsker dig med en vellykket registrering. Vores system er optaget i øjeblikket. Vores konsulent kontakter dig snarest.",
            7: "Desværre kan dine registreringsdata ikke accepteres af vores system. Prøv venligst at udfylde formularen med forskellige data."
        },
        "preferredCountryList": ["no", "se", "de", "fl", "is", "nl"],
        "country": "dk"
    },
    "es": {
        "messages": {
            "fullname": "- campo obligatorio <br> - el campo debe contener solo letras",
            "firstname": "- campo obligatorio <br> - longitud del nombre 2-26 caracteres <br> - el campo debe contener solo letras",
            "lastname": "- campo obligatorio <br> - longitud del nombre 2-26 caracteres <br> - el campo debe contener solo letras",
            "email": "- el campo debe contener una dirección de correo electrónico válida",
            "phone": "- número ingresado incorrectamente",
            "conditions": "Por favor confirme su acuerdo con las condiciones",
            "success": "Todo fue exitoso, ¡te felicitamos!",
            "error": "Lamentablemente, el envío no fue exitoso",
            "limit": "Desafortunadamente, el límite de envío ha expirado",
            "code": "Ha introducido un código incorrecto",
            "required": "Campo requerido",
            0: "Lo felicitamos con el registro exitoso. Nuestro consultor se pondrá en contacto con usted en breve.",
            1: "Lo felicitamos con el registro exitoso. Nuestro consultor se pondrá en contacto con usted en breve. Serás redirigido a tu cuenta personal en unos segundos.",
            2: "Su dirección de correo electrónico se utilizó anteriormente para registrarse en su sistema. Por favor, intente un correo electrónico diferente.",
            3: "Lo felicitamos con el registro exitoso. Nuestro consultor se pondrá en contacto con usted en breve.",
            4: "Lamentablemente, hubo un error durante el registro. Por favor, inténtelo de nuevo más tarde.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Lo felicitamos con el registro exitoso. Nuestro sistema está ocupado en este momento. Nuestro consultor se pondrá en contacto con usted en breve.",
            7: "Desafortunadamente, su información de registro no puede ser aceptada por nuestro sistema. Intente completar el formulario con diferentes datos."
        },
        "preferredCountryList": ["pt", "fr", "ma", "dz"],
        "country": "es"
    },
    "fi": {
        "messages": {
            "fullname": "- pakollinen kenttä <br> - kenttä saa sisältää vain kirjaimia",
            "firstname": "- pakollinen kenttä <br> - nimen pituus 2-26 merkkiä <br> - kenttä saa sisältää vain kirjaimia",
            "lastname": "- pakollinen kenttä <br> - nimen pituus 2-26 merkkiä <br> - kenttä saa sisältää vain kirjaimia",
            "email": "- kentässä on oltava voimassa oleva sähköpostiosoite",
            "phone": "- numero on kirjoitettu väärin",
            "conditions": "Vahvista sopimuksesi ehdoilla",
            "success": "Kaikki onnistui, onnittelemme sinua!",
            "error": "Valitettavasti lähettäminen ei onnistunut",
            "limit": "Valitettavasti lähetysraja on vanhentunut",
            "code": "Annoit väärän koodin",
            "required": "vaadittu kenttä",
            0: "Onnittelemme sinua onnistuneella rekisteröinnillä. Konsulttimme ottaa sinuun yhteyttä lähiaikoina.",
            1: "Onnittelemme sinua onnistuneella rekisteröinnillä. Konsulttimme ottaa sinuun yhteyttä lähiaikoina. Sinut ohjataan henkilökohtaiseen tiliisi muutamassa sekunnissa.",
            2: "Sähköpostiosoitettasi käytettiin aiemmin rekisteröintiin järjestelmässäsi. Yritä toista sähköposti.",
            3: "Onnittelemme sinua onnistuneella rekisteröinnillä. Konsulttimme ottaa sinuun yhteyttä lähiaikoina.",
            4: "Valitettavasti tapahtui virhe rekisteröinnin aikana. Yritä uudelleen myöhemmin.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Onnittelemme sinua onnistuneella rekisteröinnillä. Järjestelmämme on tällä hetkellä kiireinen. Konsulttimme ottaa sinuun yhteyttä lähiaikoina.",
            7: "Valitettavasti järjestelmämme ei voi hyväksyä rekisteröintitietoja. Yritä täyttää lomake erilaisilla tiedoilla."
        },
        "preferredCountryList": ["no", "se", "se", "is", "ru"],
        "country": "fi"
    },
    "fr": {
        "messages": {
            "fullname": "- champ obligatoire <br> - le champ ne doit contenir que des lettres",
            "firstname": "- champ obligatoire <br> - longueur du nom 2-26 caractères <br> - le champ ne doit contenir que des lettres",
            "lastname": "- champ obligatoire <br> - longueur du nom 2-26 caractères <br> - le champ ne doit contenir que des lettres",
            "email": "- le champ doit contenir une adresse email valide",
            "phone": "- nombre entré incorrectement",
            "conditions": "Veuillez confirmer votre accord avec les conditions",
            "success": "Tout a été un succès, nous vous félicitons!",
            "error": "Malheureusement, l'envoi n'a pas réussi",
            "limit": "Malheureusement, la limite d'envoi a expiré",
            "code": "You entered an incorrect code",
            "required": "champs requis",
            0: "Nous vous félicitons pour votre inscription réussie. Notre consultant vous contactera sous peu.",
            1: "Nous vous félicitons pour votre inscription réussie. Notre consultant vous contactera sous peu. Vous serez redirigé vers votre compte personnel dans quelques secondes.",
            2: "Votre adresse e-mail a déjà été utilisée pour l'enregistrement dans votre système. S'il vous plaît essayez un autre email.",
            3: "Nous vous félicitons pour votre inscription réussie. Notre consultant vous contactera sous peu.",
            4: "Malheureusement, il y a eu une erreur lors de l'inscription. Veuillez réessayer plus tard.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Nous vous félicitons pour votre inscription réussie. Notre système est occupé en ce moment. Notre consultant vous contactera sous peu.",
            7: "Malheureusement, vos données d'inscription ne peuvent pas être acceptées par notre système. S'il vous plaît essayez de remplir le formulaire avec des données différentes."
        },
        "preferredCountryList": ["ge", "be", "it", "lu"],
        "country": "fr"
    },
    "it": {
        "messages": {
            "fullname": "- campo obbligatorio <br> - il campo deve contenere solo lettere",
            "firstname": "- campo obbligatorio <br> - lunghezza del nome 2-26 caratteri <br> - il campo deve contenere solo lettere",
            "lastname": "- campo obbligatorio <br> - lunghezza del nome 2-26 caratteri <br> - il campo deve contenere solo lettere",
            "email": "- il campo deve contenere un indirizzo email valido",
            "phone": "- numero inserito in modo errato",
            "conditions": "Si prega di confermare il vostro accordo con le condizioni",
            "success": "Tutto ha avuto successo, ci congratuliamo con te!",
            "error": "Sfortunatamente, l'invio non ha avuto successo",
            "limit": "Sfortunatamente, il limite di invio è scaduto",
            "code": "You entered an incorrect code",
            "required": "Campo requerido",
            0: "Ci congratuliamo con la registrazione avvenuta con successo. Il nostro consulente ti contatterà a breve.",
            1: "Ci congratuliamo con la registrazione avvenuta con successo. Il nostro consulente ti contatterà a breve. Verrai reindirizzato al tuo account personale in pochi secondi.",
            2: "Il tuo indirizzo email è stato precedentemente utilizzato per la registrazione nel tuo sistema. Si prega di provare una e-mail diversa.",
            3: "Ci congratuliamo con la registrazione avvenuta con successo. Il nostro consulente ti contatterà a breve.",
            4: "Sfortunatamente, c'è stato un errore durante la registrazione. Per favore riprova più tardi.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Ci congratuliamo con la registrazione avvenuta con successo. Il nostro sistema è occupato al momento. Il nostro consulente ti contatterà a breve.",
            7: "Sfortunatamente, i tuoi dati di registrazione non possono essere accettati dal nostro sistema. Si prega di provare a compilare il modulo con dati diversi."
        },
        "preferredCountryList": ["ge", "be", "fr", "lu"],
        "country": "it"
    },
    "no": {
        "messages": {
            "fullname": "- obligatorisk felt <br> - felt må bare inneholde bokstaver",
            "firstname": "- obligatorisk felt <br> - navnelengde 2-26 tegn <br> - felt må bare inneholde bokstaver",
            "lastname": "- obligatorisk felt <br> - navnelengde 2-26 tegn <br> - felt må bare inneholde bokstaver",
            "email": "- feltet må inneholde en gyldig e-postadresse",
            "phone": "- nummeret er skrevet feil",
            "conditions": "Vennligst bekreft din avtale med vilkårene",
            "success": "Alt var vellykket, vi gratulerer med deg!",
            "error": "Dessverre var sendingen ikke vellykket",
            "limit": "Dessverre er sendegrensen utløpt",
            "code": "You entered an incorrect code",
            0: "Vi gratulerer deg med vellykket registrering. Vår konsulent vil kontakte deg snart.",
            1: "Vi gratulerer deg med vellykket registrering. Vår konsulent vil kontakte deg snart. Du blir omdirigert til din personlige konto om noen få sekunder.",
            2: "Din e-postadresse ble tidligere brukt til registrering i vårt system. Vennligst prøv en annen epost.",
            3: "Vi gratulerer deg med vellykket registrering. Vår konsulent vil kontakte deg snart.",
            4: "Dessverre var det en feil under registreringen. Prøv igjen senere.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Vi gratulerer deg med vellykket registrering. Vårt system er opptatt for øyeblikket. Vår konsulent vil kontakte deg snart.",
            7: "Dessverre kan ikke registreringsdataene aksepteres av vårt system. Vennligst prøv å fylle ut skjemaet med forskjellige data."
        },
        "preferredCountryList": ["se", "de", "fl", "is", "nl"],
        "country": "no"
    },
    "pt": {
        "messages": {
            "fullname": "- campo obrigatório <br> - o campo deve conter apenas letras",
            "firstname": "- campo obrigatório <br> - comprimento do nome de 2 a 26 caracteres <br> - o campo deve conter apenas letras",
            "lastname": "- campo obrigatório <br> - comprimento do nome de 2 a 26 caracteres <br> - o campo deve conter apenas letras",
            "email": "- campo deve conter um endereço de email válido",
            "phone": "- número digitado incorretamente",
            "conditions": "Por favor, confirme sua concordância com as condições",
            "success": "Tudo foi bem sucedido, parabenizamos você!",
            "error": "Infelizmente, o envio não foi bem sucedido",
            "limit": "Infelizmente, o limite de envio expirou",
            "code": "You entered an incorrect code",
            "required": "Obligatorisk felt",
            0: "Parabenizamos você pelo registro bem-sucedido. Nosso consultor entrará em contato com você em breve.",
            1: "Parabenizamos você pelo registro bem-sucedido. Nosso consultor entrará em contato com você em breve. Você será redirecionado para sua conta pessoal em poucos segundos.",
            2: "Seu endereço de e-mail foi usado anteriormente para registro em nosso sistema. Por favor tente um email diferente.",
            3: "Parabenizamos você pelo registro bem-sucedido. Nosso consultor entrará em contato com você em breve.",
            4: "Infelizmente, houve um erro durante o registro. Por favor, tente novamente mais tarde.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Parabenizamos você pelo registro bem-sucedido. Nosso sistema está ocupado no momento. Nosso consultor entrará em contato com você em breve.",
            7: "Infelizmente, seus dados cadastrais não podem ser aceitos pelo nosso sistema. Por favor, tente preencher o formulário com dados diferentes."
        },
        "preferredCountryList": ["es", "it", "fr", "ma"],
        "country": "pt"
    },
    "se": {
        "messages": {
            "fullname": "- obligatoriskt fält <br> - fält får endast innehålla bokstäver",
            "firstname": "- obligatoriskt fält <br> - namnlängd 2-26 tecken <br> - fält får endast innehålla bokstäver",
            "lastname": "- obligatoriskt fält <br> - namnlängd 2-26 tecken <br> - fält får endast innehålla bokstäver",
            "email": "- Fältet måste innehålla en giltig e-postadress",
            "phone": "- Talat in felaktigt",
            "conditions": "Vänligen bekräfta ditt avtal med villkoren",
            "success": "Allt lyckades, vi gratulerar dig!",
            "error": "Tyvärr var sändningen inte framgångsrik",
            "limit": "Tyvärr har sändningsgränsen löpt ut",
            "code": "du matade in en felaktig kod",
            "required": "obligatoriskt fält",
            0: "Vi gratulerar dig med framgångsrik registrering. Vår konsult kommer snart att kontakta dig.",
            1: "Vi gratulerar dig med framgångsrik registrering. Vår konsult kommer snart att kontakta dig. Du kommer att omdirigeras till ditt personliga konto inom några sekunder.",
            2: "Din e-postadress användes tidigare för registrering i ditt system. Var god försök med ett annat email.",
            3: "Vi gratulerar dig med framgångsrik registrering. Vår konsult kommer snart att kontakta dig.",
            4: "Tyvärr uppstod ett fel vid registrering. Vänligen försök igen senare.",
            5: "Unfortunately, there are no suitable brokers for you.",
            6: "Vi gratulerar dig med framgångsrik registrering. Vårt system är upptagen för tillfället. Vår konsult kommer snart att kontakta dig.",
            7: "Tyvärr kan din registreringsdata inte godtas av vårt system. Vänligen försök fylla i formuläret med olika uppgifter."
        },
        "preferredCountryList": ["fl", "no", "se", "is", "nl"],
        "country": "se"
    },
    "pl": {
        "messages": {
            "fullname": "- pole obowiązkowe <br>- pole musi zawierać tylko litery",
            "firstname": "- pole obowiązkowe <br>- длина имени 2-26 символова<br>- pole musi zawierać tylko litery",
            "lastname": "- pole obowiązkowe <br>- длина имени 2-26 символова<br>- pole musi zawierać tylko litery",
            "email": "- pole musi zawierać poprawny adres e-mail ",
            "phone": "- pole musi zawierać poprawny numer telefonu",
            "conditions": "Prosimy o potwierdzenie akceptacji warunków i zasad ",
            "success": "Gratulacje! Państwa rejestracja przebiegła pomyślnie! Oczekujcie wkrótce kontaktu telefonicznego",
            "error": "Niestety, rejestracja nie powiodła się ",
            "limit": "Przykro nam, ale limit zgłoszeń został wyczerpany. ",
            "code": "pole musi zawierać prawidłowy kod",
            "required": "pole obowiązkowe",
            0: "Gratulujemy udanej rejestracji. Wkrótce skontaktuje się z Państwem Państwa osobisty doradca.",
            1: "Gratulujemy udanej rejestracji. Wkrótce skontaktuje się z Państwem Państwa osobisty doradca. W ciągu kilku sekund zostaną Państwo przekierowani na swoje konto osobiste.",
            2: "Państwa adres e-mail jest już zarejestrowany w systemie. Proszę spróbować innego adresu.",
            3: "Gratulujemy udanej rejestracji. Wkrótce skontaktuje się z Państwem Państwa osobisty doradca.",
            4: "Przepraszamy, wystąpił błąd podczas rejestracji. Prosimy spróbować ponownie później.",
            5: "Przepraszamy, nie ma odpowiednich brokerów dla Państwa w tej chwili.",
            6: "Gratulujemy udanej rejestracji. Niestety, system ten jest obecnie niedostępny. Wkrótce skontaktuje się z Państwem Państwa osobisty doradca.",
            7: "Niestety, wprowadzone dane nie mogą być zaakceptowane przez system. Proszę spróbować innych szczegółów rejestracji."
        },
        "preferredCountryList": ["kz", "ua", "by", "ge"],
        "country": "pl"
    }
}